### ISSUE TITLE
TOPIC is missing

### ISSUE THREAD

**Issue by fisero** [charlielito/node-red-contrib-sensor-ds18b20#1]
Topic is missing in produced message. Even if Name/Topic is filled.

**Comment by charlielito** [comment]
You are right! I missed that part, I'll fix it and release a new version! Thanks

**Comment by mboremski** [comment]
could you have a look on this again..
"topic" is still missing..

**Comment by charlielito** [comment]
Hi, sorry I forgot to look into this. It is now fixed in the new version now available.
